name: terralith
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    
  google_fonts: ^6.2.1
  firebase_core: ^3.7.0
  get: ^4.6.6

  flutter_easyloading: ^3.0.5
  flutter_widget_from_html: ^0.15.3
  youtube_player_flutter: ^9.1.1

  auto_size_text: ^3.0.0
  syncfusion_flutter_pdfviewer: ^27.2.5

  flutter_native_splash: ^2.4.4

  # firebase
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5

  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/avatars/
    - assets/materi/
    - assets/materi/pdf/

flutter_native_splash:
  color: "#001F3F"
  image: assets/logo_icon_app.png
  branding: assets/TERRALITH.png
  branding_bottom_padding: 34

  android_12:
    image: assets/logo_icon_app.png
    color: "#001F3F"


icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/logo_icon_app.png"
      adaptive_foreground_image: "assets/ic_foreground.png"
      adaptive_background_image: "assets/ic_background.png"
    ios:
      enable: true
      image_path: "assets/logo_icon_app.png"